- 1.1.13+dfsg-1
- _NAME: Marathon Mouse M705 (M-R0073)
  _absent: [hi-res-scroll, lowres-scroll-mode, scroll-ratchet, smart-shift, thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended,
    dpi, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered,
    backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting, fn-swap, persistent-remappable-keys, disable-keyboard-keys,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, sidetone,
    equalizer, adc_power_management]
  _battery: 4096
  _modelId: 406D00000000
  _sensitive: {divert-keys: false}
  _serial: 63B382BC
  _unitId: 0A88E80E
  _wpid: 406D
  divert-keys: {82: 0, 83: 1, 86: 0, 91: 1, 93: 1}
  hires-scroll-mode: false
  hires-smooth-invert: false
  hires-smooth-resolution: true
  pointer_speed: 256
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 91: 91, 93: 93}
